### ISSUE TITLE
Disable automatic updates in org for this repo

### ISSUE THREAD

**Issue by jsumners** [fastify/workflows#108]
https://github.com/fastify/workflows/pull/107 added a `v4` tag so that we can prepare for `fastify@5` across all repos. Unfortunately, Dependabot started updating all of our repos from `workflows@3` to `workflows@4`. And then an automation (https://github.com/fastify/workflows/pull/107#issuecomment-1789536706) started merging them.

We need to disable this automation for the `workflows` repo across all projects. We will only ever release a new major of `workflows` that imposes a major change in all repos that depend upon it.

attn: @mcollina @Fdawgs

**Comment by nrayburn-tech** [comment]
Is there a better way to do this other than what is being done for the tap dependency? https://github.com/fastify/fastify/issues/5116#issuecomment-1790152300

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore

General syntax I think (not sure about the dependency-name, haven't been able to find docs for referring to the github action name).
```yaml
updates:
  - package-ecosystem: "github-actions"
    groups:
        ignore:
        - dependency-name: "plugins-ci"
          update-types: ["version-update:semver-major"]
```
