### ISSUE TITLE
Workflow for official Fastify Demo

### ISSUE THREAD

**Issue by jean-michelet** [fastify/workflows#133]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Maybe we should create a workflow for the [Official Fastify Demo](https://github.com/fastify/demo/pull/1) .

### Motivation

As the demo is not a plugin, I'm having trouble using an existing workflow, but maybe you have a solution, that I can modify an existing workflow like the one for the mysql plugin.

It wouldn't designed to be shared, but it might be easier to have all the workflows in one place when upgrading versions.

### Example

```yml
name: CI
on:
  push:
    branches:
      - main
      - next
      - "v*"
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
jobs:
  test:
    uses: fastify/workflows/.github/workflows/demo-ci.yml@v4.1.0
    with:
      license-check: true
      lint: true
```
