### ISSUE TITLE
proposal: ignore push events for dependabot branches

### ISSUE THREAD

**Issue by Uzlopak** [fastify/workflows#56]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

When dependabot opens a PR to update a dependency, it runs the whole ci pipeline twice. Once by push and once by pull request event. We could actually save one ci run when we would ignore the dependabot branch in push events.

We could actually configure, that only push events into master, main and next result in a pipeline run.

**Comment by Fdawgs** [comment]
Will take a look.

Less CI runs would mean less resources/bandwidth wasted and less time waiting.

**Comment by Uzlopak** [comment]
Exactly. When we e.g. activated license-check it always run twice, clogging the github runners.

Thank you. :)

**Comment by Fdawgs** [comment]
something like:

```yml
on:
  push:
    branches:
     - main
     - master
     - next
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
```

would solve this, not just for Dependabot PRs but for all PRs. Your recent PR to fastify-helmet ran it twice as well: https://github.com/fastify/fastify-helmet/pull/195
