### ISSUE TITLE
Benchmark workflow

### ISSUE THREAD

**Issue by Uzlopak** [fastify/workflows#89]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

We should have a nice benchmark workflow for use in different repos.

While writing the benchmark workflow of fsj, i saw some issues, which should be tackled:

- [ ] the pr comment action is using node 12 and results in warnings. I am pretty sure we can use octokit/request-action instead
- [x] we should use the new way to handle outputs, see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ . I tried to use it, but there a formatting issues which dont work with the new way of outputting information.
- [ ] we should think of a way to handle a matrix strategy for the node version. Input variables can not be array. So we should check if you are just pass a comma separated list, where we slab brackets around and the use the json parse method of the github runner. This we could use for the other workflows here in this repo too. But for fsj, i dont need benchmarks from node14 to node 20. I just need one, and thats the lts.
- [ ] we need to investigate a nice way to create the pull request body.
- [ ] we should use the default_branch information from the event instead of hardcoding 'master' or 'main'. Maybe use an input variable, where default is the default_branch?

**Comment by Uzlopak** [comment]
@Fdawgs 
@RafaelGSS

**Comment by Uzlopak** [comment]
Multiline works with this: https://github.com/github/docs/issues/21529

Tested it

**Comment by Uzlopak** [comment]
Removing a label 

```yaml
  remove-label:
    if: "always()"
    needs: 
      - benchmark
      - output-benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Remove benchmark label
        uses: octokit/request-action@v2.x
        id: remove-label
        with:
          route: DELETE /repos/{repo}/issues/{issue_number}/labels/{name}
          repo: ${{ github.event.pull_request.head.repo.full_name }}
          issue_number: ${{ github.event.pull_request.number }}
          name: benchmark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
